# Timeout in seconds that Limine will use before automatically booting.
timeout: 0

# The entry name that will be displayed in the boot menu.
/cavOS
    # We use the Limine boot protocol.
    protocol: limine

    # Disable KASLR (it is enabled by default for relocatable kernels)
    kaslr: yes

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/kernel.bin